name: healio_version_2
description: "A modern, Flutter-powered project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.1 <4.0.0'  # Ensures compatibility with Dart 3.8+

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # HTTP Client
  dio: ^5.7.0

  # Local Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.3.3
  

  # Database
  sqflite: ^2.4.0

  # Authentication
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.2

  # Real-time Communication
  socket_io_client: ^3.0.2
  web_socket_channel: ^3.0.1

  # Video/Voice Calls
 
  permission_handler: ^12.0.1

  # Chat Features
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0



  # Push Notifications
  firebase_messaging: ^15.1.3

  # UI Components
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # Date/Time
  intl: ^0.19.0

  # Location
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  # Utils
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  connectivity_plus: ^6.1.1
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0
  image_picker: ^0.8.7+6

  # Security
  crypto: ^3.0.6

  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.2

  # Toast (fixed!)
  fluttertoast: ^8.2.12
  
  file_picker: ^10.3.2
  camera: ^0.11.2
  agora_rtc_engine: ^6.5.2
  

  iconsax: ^0.0.8
  table_calendar: ^3.0.9

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/logo.png"


flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/avatars/
    - lib/assets/images/icons/
    - lib/assets/images/logo/
    - lib/assets/images/onboarding/
    - lib/assets/images/patient/
    - lib/assets/images/doctors/
    - lib/assets/vectors/
    - lib/assets/images/
    - lib/assets/icons/

  fonts:
    - family: Notosans
      fonts:
        - asset: lib/assets/fonts/Notosans-Regular.ttf
        - asset: lib/assets/fonts/Notosans-Italic.ttf
          weight: 500
        - asset: lib/assets/fonts/Notosans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Notosans-BoldItalic.ttf
          weight: 900

    - family: Notoserif
      fonts:
        - asset: lib/assets/fonts/Notoserif-Regular.ttf
        - asset: lib/assets/fonts/Notoserif-Italic.ttf
          weight: 500
        - asset: lib/assets/fonts/Notoserif-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Notoserif-BoldItalic.ttf
          weight: 900
